version: '3.8'

services:
  app:
    build: .
    command: pipenv run supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - lun_network

  redis:
    image: redis
    container_name: redis
    networks:
      - lun_network

networks:
  lun_network:
    driver: bridge
