version: '3.8'

services:
  bot:
    build: .
    command: pipenv run python /app/bot.py
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - lun_network
    restart: always

  huey_worker:
    build: .
    command: pipenv run huey_consumer.py core.tasks.huey
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - lun_network

  redis:
    image: redis
    container_name: redis
    networks:
      - lun_network

networks:
  lun_network:
    driver: bridge